[package]
name = "rill"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]
description = "Precise logging system"
edition = "2018"
categories = ["development-tools::debugging"]
keywords = ["logging"]

[dependencies]
